version: "3.5"
services:
  hsmq:
    image: hsmq
    build: .
    ports:
      - 4848-4855:4848
    volumes:
      - ${PWD}/hsmq.toml:/etc/hsmq.toml
    environment:
      RUST_LOG: error
      TOKEN: 123
    networks: ["hsmq"]

  redis:
    image: grokzen/redis-cluster:6.2.1
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
    environment:
      IP: 0.0.0.0
      INITIAL_PORT: 7000

networks:
  hsmq:
    name: hsmq
