[node]
# grpc_address = "[::1]:4848"  # IPv6
grpc_address = "0.0.0.0:4848"  # IPv4

[auth.jwt]
secrets = [
    # "inline secret",
    { env = "JWT_SECRET" }, # secret from environment variable
]

[cluster]
name = "c1"
udp_port = 4848

[prometheus]
url = "/metrics"
http_address = "0.0.0.0:8080"

[[queues]]
type = "InMemory"
name = "a"
limit = 99
ack_timeout = {h = 4}
topics = [
    "a.b",
]

[[queues]]
type = "RedisStream"
name = "redis-stream"
connector = "redis-local"
group = "redis-stream"
init_group = true
nomkstream = false
maxlen = 999
limit = 99
read_limit = 14
ack_timeout = 100
topics = [
    # "b.a",
    "redis-stream",
]
streams = [
    "stream:key:0",
    "stream:key:1",
    "stream:key:2",
    "stream:key:3",
    "stream:key:4",
    "stream:key:5",
    "stream:key:6",
    "stream:key:7",
    "stream:key:8",
    "stream:key:9",
    "stream:key:A",
    "stream:key:B",
    "stream:key:C",
    "stream:key:D",
    "stream:key:E",
    "stream:key:F",
]

[redis.redis-local]
nodes = [
    "redis://localhost:7000",
]
# username = "a1"
# password = {env = "REDIS_PASSWORD"}

[[queues]]
type = "InMemory"
name = "b"
limit = 99
ack_timeout = 1
topics = [
    "b.a",
]

[users.my_username]
tokens = [
    # "inline personal token",
    { env = "TOKEN" }, # token from environment variable
]
