name: Clippy

env:
  RUSTFLAGS: "-Dwarnings"

on:
  push:
    branches:
      - 'main'
    tags: [ '*' ]
  pull_request:
    branches:
      - 'main'

jobs:
  clippy:
    name: Rust Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: sudo apt install -y protobuf-compiler
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
