name: Rustfmt

env:
  RUSTFLAGS: "-Dwarnings"

on:
  push:
    branches:
      - 'main'
    tags: [ '*' ]
  pull_request:
    branches:
      - 'main'

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: cargo fmt
        run: cargo fmt --all -- --check
